server:
  port: 8765
spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED}
          lower-case-service-id: ${SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID}
      routes:
        - id: content-service-route
          uri: lb://content-service
          predicates:
            - Path=/content/**
        - id: email-service-route
          uri: lb://email-service
          predicates:
            - Path=/emails/**
        - id: mailing-service-route
          uri: lb://mailing-service
          predicates:
            - Path=/mailing/**
        - id: message-service-route
          uri: lb://message-service
          predicates:
            - Path=/messages/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    preferIpAddress: ${EUREKA_INSTANCE_PREFERIPADDRESS}